### ISSUE TITLE
react-native-css-interop incompatible with react-native-reanimated 3.17.x - Android build fails

### ISSUE THREAD

**Issue by mkshaonexe** [nonbili/NouTube#84]
Environment
OS: Windows 11
Expo SDK: 53.0.24
React Native: 0.79.6
NativeWind: 4.2.1
react-native-reanimated: 3.17.5
react-native-css-interop: 0.2.1
Build Platform: EAS Build (Expo Application Services)
Problem
Android builds fail when using NativeWind with Expo SDK 53. The issue is a conflict between react-native-css-interop (used by NativeWind) and react-native-reanimated 3.17.x.

Error 1: Missing react-native-worklets/plugin
When building without react-native-worklets installed: SyntaxError: [BABEL] Cannot find module 'react-native-worklets/plugin' 

Error 2: Native code redefinition conflict
When installing react-native-worklets to fix Error 1: 

error: redefinition of 'NativeWorkletsModuleSpecJSI'
  /node_modules/react-native-worklets/android/.../rnworklets.h:22:18: error
  /node_modules/react-native-reanimated/android/.../rnreanimated.h:30:18: note: previous definition is here

Expected Behavior
NativeWind should work with react-native-reanimated 3.17.x without requiring manual patches.

This affects all users of NativeWind 4.x with Expo SDK 53
The issue is specific to Android builds (iOS may work differently)
Local builds on Windows 11 also fail with the same errors

<img width="1692" height="688" alt="Image" src="https://github.com/user-attachments/assets/5e6eeb1f-6a54-4d5d-a4a7-347982e6500f" />
